var dataMain =  [
		            {"id":"root", "isroot":true, "topic":"收入降收"},
			            {"id":"11", "parentid":"root", "topic":"显性<span>20325.63万元</span>"},
			            	/*{"id":"111", "parentid":"11", "topic":"用户流失<span>58.73%/11937.99万元</span>"},
			            		{"id":"1111", "parentid":"111", "topic":"用户质量问题<span>16.03%/1914.18万元</span>"},
			            			{"id":"11111", "parentid":"1111", "topic":"虚假<span>0.07%/1.29万元</span>"},
			            			{"id":"11112", "parentid":"1111", "topic":"养卡<span>0.00%/0万元</span>"},
			            			{"id":"11113", "parentid":"1111", "topic":"极低三无<span class='important'>98.60%/1887.33万元</span>"},
			            			{"id":"11114", "parentid":"1111", "topic":"重入网<span>0.03%/0.66万元</span>"},
			            			{"id":"11115", "parentid":"1111", "topic":"拍照即异常<span>1.30%/24.89万元</span>"},
			            		{"id":"1112", "parentid":"111", "topic":"正常用户发成行为变化<span>1.70%/203.24万元</span>"},
			            			{"id":"11121", "parentid":"1112", "topic":"网络不匹配<span>30.82%/62.64万元</span>"},
			            			{"id":"11122", "parentid":"1112", "topic":"备卡型<span class='important'>40.70%/82.72万元</span>"},
			            			{"id":"11123", "parentid":"1112", "topic":"本地转异地<span>0.44%/0.89万元</span>"},
			            			{"id":"11124", "parentid":"1112", "topic":"语音使用行为巨变<span>2.73%/5.54万元</span>"},
			            			{"id":"11125", "parentid":"1112", "topic":"流量使用行为巨变<span>3.48%/7.07万元</span>"},
			            			{"id":"11126", "parentid":"1112", "topic":"合约到期未续约<span>21.84%/44.38万元</span>"},
			            		{"id":"1113", "parentid":"111", "topic":"其他<span>82.26%/9820.57万元</span>"},*/
			            	{"id":"112", "parentid":"11", "topic":"在网用户降收<span>41.27%/8387.64万元</span>"},
			            		{"id":"1121", "parentid":"112", "topic":"产品结构变化<span>71.40%/5988.78万元</span>"},
			            			{"id":"11211", "parentid":"1121", "topic":"合约发生变化<span>17.90%/1071.70万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11212", "parentid":"1121", "topic":"套餐变化<span>26.31%/1575.94万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11213", "parentid":"1121", "topic":"产品不变资费变化<span class='important'>55.79%/3341.13万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1122", "parentid":"112", "topic":"用戶使用费变化<span>18.86%/1581.62万元</span>"},
			            			{"id":"11221", "parentid":"1122", "topic":"国际漫游<span>4.51%/71.41万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11222", "parentid":"1122", "topic":"语音费下降<span class='important'>36.41%/575.93万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11223", "parentid":"1122", "topic":"流量费下降<span>36.07%/570.43万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11224", "parentid":"1122", "topic":"语音费流量费皆下降<span>23.00%/363.85万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1123", "parentid":"112", "topic":"财务变化<span>0.00%/0万元</span>"},
			            			{"id":"11231", "parentid":"1123", "topic":"调账<span>0%/0万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1124", "parentid":"112", "topic":"其他<span>9.74%/817.64万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"12", "parentid":"root", "topic":"隐性<span>3179586人</span>"},
			            	{"id":"121", "parentid":"12", "topic":"用户使用量下降<span class='important'>3179586人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"122", "parentid":"12", "topic":"流失倾向<span>162705</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"123", "parentid":"12", "topic":"产品变化<span>54820人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
		        ]

var dataMain2 =  [
		            {"id":"root", "isroot":true, "topic":"收入降收"},
			            {"id":"11", "parentid":"root", "topic":"显性<span>6937.29万元</span>"},
			            	{"id":"111", "parentid":"11", "topic":"用户流失<span>18.13%/1257.47万元</span>"},
			            		{"id":"1111", "parentid":"111", "topic":"用户质量问题<span>58.76%/738.85万元</span>"},
			            			{"id":"11111", "parentid":"1111", "topic":"虚假<span>0.13%/0.96万元</span>"},
			            			{"id":"11112", "parentid":"1111", "topic":"养卡<span>0.00%/0万元</span>"},
			            			{"id":"11113", "parentid":"1111", "topic":"极低三无<span class='important'>95.88%/708.42万元</span>"},
			            			{"id":"11114", "parentid":"1111", "topic":"重入网<span>0.03%/0.25万元</span>"},
			            			{"id":"11115", "parentid":"1111", "topic":"拍照即异常<span>3.95%/29.22万元</span>"},
			            		{"id":"1112", "parentid":"111", "topic":"正常用户发成行为变化<span>5.71%/71.84万元</span>"},
			            			{"id":"11121", "parentid":"1112", "topic":"网络不匹配<span>38.40%/27.59万元</span>"},
			            			{"id":"11122", "parentid":"1112", "topic":"备卡型<span class='important'>12.17%/8.74万元</span>"},
			            			{"id":"11123", "parentid":"1112", "topic":"本地转异地<span>0.00%/0万元</span>"},
			            			{"id":"11124", "parentid":"1112", "topic":"语音使用行为巨变<span>6.18%/4.44万元</span>"},
			            			{"id":"11125", "parentid":"1112", "topic":"流量使用行为巨变<span>14.89%/10.70万元</span>"},
			            			{"id":"11126", "parentid":"1112", "topic":"合约到期未续约<span>28.34%/20.36万元</span>"},
			            		{"id":"1113", "parentid":"111", "topic":"其他<span>35.53%/446.78万元</span>"},
			            	{"id":"112", "parentid":"11", "topic":"在网用户降收<span>81.87%/5679.82万元</span>"},
			            		{"id":"1121", "parentid":"112", "topic":"产品结构变化<span>54.14%/3075.26万元</span>"},
			            			{"id":"11211", "parentid":"1121", "topic":"合约发生变化<span>2.42%/74.45万元</span>"},
			            			{"id":"11212", "parentid":"1121", "topic":"套餐变化<span>6.43%/197.60万元</span>"},
			            				{"id":"112121", "parentid":"11212", "topic":"套餐类型变化升套<span>0.61%/18.77万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            				{"id":"112122", "parentid":"11212", "topic":"套餐类型变化降套<span>0.52%/16.14万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            				{"id":"112123", "parentid":"11212", "topic":"套餐类型变化不确定<span class='important'>0.24%/7.39万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            				{"id":"112124", "parentid":"11212", "topic":"套餐类型不变升套<span>0.03%/0.85万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            				{"id":"112125", "parentid":"11212", "topic":"套餐类型不变降套<span>0.09%/2.70万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            				{"id":"112126", "parentid":"11212", "topic":"套餐类型不变不确定<span>4.93%/151.74万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11213", "parentid":"1121", "topic":"合约、套餐不变资费变化<span class='important'>0.00%/0万元</span>"},
			            		{"id":"1122", "parentid":"112", "topic":"用戶使用费变化<span>35.24%/2001.46万元</span>"},
			            			{"id":"11221", "parentid":"1122", "topic":"国际漫游<span>3.77%/75.49万元</span>"},
			            			{"id":"11222", "parentid":"1122", "topic":"语音费下降<span>27.01%/540.50万元</span>"},
				            			{"id":"112221", "parentid":"11222", "topic":"包套<span class='important'>26.08%/522.08万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            			{"id":"112222", "parentid":"11222", "topic":"无包套<span>0.92%/18.42万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11223", "parentid":"1122", "topic":"流量费下降<span>45.30%/906.62万元</span>"},
				            			{"id":"112231", "parentid":"11223", "topic":"包套<span class='important'>45.04%/901.41万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            			{"id":"112232", "parentid":"11223", "topic":"无包套<span>0.26%/5.21万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            			{"id":"11224", "parentid":"1122", "topic":"语音费流量费皆下降<span>23.92%/478.84万元</span>"},
				            			{"id":"112241", "parentid":"11224", "topic":"包套<span class='important'>23.68%/473.94万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            			{"id":"112242", "parentid":"11224", "topic":"无包套<span>0.24%/4.90万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1123", "parentid":"112", "topic":"财务变化<span>0.00%/0万元</span>"},
			            			{"id":"11231", "parentid":"1123", "topic":"调账<span>0%/0万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1124", "parentid":"112", "topic":"其他<span>12.06%/685.26万元</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"12", "parentid":"root", "topic":"隐性<span>2758632人</span>"},
			            	{"id":"121", "parentid":"12", "topic":"用户使用量下降<span>2548095人</span>"},
			            		{"id":"1211", "parentid":"121", "topic":"40%-60%<span class='important'>552840人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1212", "parentid":"121", "topic":"60%+<span>2087347人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"122", "parentid":"12", "topic":"流失倾向<span>211772人</span>"},
			            		{"id":"1221", "parentid":"122", "topic":"准流失用户<span>211772人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1222", "parentid":"122", "topic":"高流失倾向<span class='important'>615585人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"123", "parentid":"12", "topic":"产品变化<span>50676人</span>"},
			            		{"id":"1231", "parentid":"123", "topic":"预约产品变化<span class='important'>25338人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
		        ]

var dataPolicy =[
		            {"id":"root", "isroot":true, "topic":"策略匹配"},
			            {"id":"11", "parentid":"root", "topic":"流失预警"},
			            	{"id":"111", "parentid":"11", "topic":"均衡型流量卡"},
			            		{"id":"1111", "parentid":"111", "topic":"53元套餐<span>(21万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1112", "parentid":"111", "topic":"83元套餐<span>(21万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"112", "parentid":"11", "topic":"畅越冰激凌<span>(21万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"113", "parentid":"11", "topic":"红包卡"},
			            		{"id":"1131", "parentid":"113", "topic":"小红包卡<span>(30万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1132", "parentid":"113", "topic":"大红包卡<span>(3万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            		{"id":"1133", "parentid":"113", "topic":"至尊红包卡<span>(11万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"12", "parentid":"root", "topic":"合约续约维系"},
			            	{"id":"121", "parentid":"12", "topic":"存费送费<span>(30万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"122", "parentid":"12", "topic":"存费送机<span>(21万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"13", "parentid":"root", "topic":"承诺低消送流量"},
			            	{"id":"131", "parentid":"13", "topic":"承诺100元送1GB<span>(10万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"132", "parentid":"13", "topic":"承诺120元送2GB<span>(1万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"14", "parentid":"root", "topic":"登录4G"},
			            	{"id":"141", "parentid":"14", "topic":"持4G终端用3G网络：赠送流量+电话引导使用4G流量<span>(11万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"142", "parentid":"14", "topic":"持2G终端：存流量送手机<span>(10万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"15", "parentid":"root", "topic":"动作营销"},
			            	{"id":"151", "parentid":"15", "topic":"赠送音乐包<span>(10万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"152", "parentid":"15", "topic":"赠送流量包500M<span>(10万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"153", "parentid":"15", "topic":"电话关怀：用户入网<=3个月<span>(13万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            	{"id":"154", "parentid":"15", "topic":"迁转冰激凌套餐<span>(30万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"16", "parentid":"root", "topic":"准流失<span>(36万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"17", "parentid":"root", "topic":"极低三无<span>(>21万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"18", "parentid":"root", "topic":"虚假养卡<span>(22万人)</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
		        ]

var dataPolicy2 =[
		            {"id":"root", "isroot":true, "topic":"策略匹配"},
			            {"id":"11", "parentid":"root", "topic":"流失预警<span>1193人</span>"},
			            {"id":"12", "parentid":"root", "topic":"合约续约维系"},
			            {"id":"13", "parentid":"root", "topic":"承诺低消送流量"},
			            {"id":"14", "parentid":"root", "topic":"登录4G"},
			            {"id":"15", "parentid":"root", "topic":"动作营销"},
			            {"id":"16", "parentid":"root", "topic":"准流失<span>18,797人</span>"},
			            {"id":"17", "parentid":"root", "topic":"极低三无"},
			            {"id":"18", "parentid":"root", "topic":"虚假养卡"},
			            {"id":"19", "parentid":"root", "topic":"2I2C用户<span>14人</span>"},
		        ]	

var dataPolicy3 =[
		            {"id":"root", "isroot":true, "topic":"策略匹配"},
			            {"id":"11", "parentid":"root", "topic":"流失预警"},
				            {"id":"111", "parentid":"11", "topic":"均衡型单卡"},
				            	{"id":"1111", "parentid":"111", "topic":"38元均衡型省内流量卡<span>427人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1112", "parentid":"111", "topic":"53元均衡型省内流量卡<span>275人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1113", "parentid":"111", "topic":"83元均衡型省内流量卡<span>477人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            {"id":"112", "parentid":"11", "topic":"畅悦冰欺凌"},
				            	{"id":"1121", "parentid":"112", "topic":"118元畅越冰激凌<span>10人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1122", "parentid":"112", "topic":"148元畅越冰激凌<span>48人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1123", "parentid":"112", "topic":"198元畅越冰激凌<span>30人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1124", "parentid":"112", "topic":"238元畅越冰激凌<span>24人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1125", "parentid":"112", "topic":"298元畅越冰激凌<span>8人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1126", "parentid":"112", "topic":"398元畅越冰激凌<span>5人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            {"id":"113", "parentid":"11", "topic":"红包卡"},
				            	{"id":"1131", "parentid":"113", "topic":"大红包<span>393人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1132", "parentid":"113", "topic":"小红包<span>161人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
				            	{"id":"1133", "parentid":"113", "topic":"至尊红包<span>75人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"12", "parentid":"root", "topic":"合约续约维系"},
			            {"id":"13", "parentid":"root", "topic":"承诺低消送流量"},
			            {"id":"14", "parentid":"root", "topic":"登录4G"},
			            {"id":"15", "parentid":"root", "topic":"动作营销"},
			            {"id":"16", "parentid":"root", "topic":"准流失"},
			            	{"id":"161", "parentid":"16", "topic":"0元500MB免费流量包"},
			            		{"id":"1611", "parentid":"161", "topic":"0元50分钟免费语音包<span>18,797人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
			            {"id":"17", "parentid":"root", "topic":"极低三无"},
			            {"id":"18", "parentid":"root", "topic":"虚假养卡"},
			            {"id":"19", "parentid":"root", "topic":"2I2C用户"},
			            	{"id":"191", "parentid":"19", "topic":"大王卡"},
			            		{"id":"1911", "parentid":"191", "topic":"0元1G国内流量资费月包<span>14人</span><input type='checkbox' class='xmindCheckbox' style='margin-left:5px;vertical-align:middle;'>"},
		        ]		   	 	

var customerFilterJSMindThumb = 	[
		            {"id":"root", "isroot":true, "topic":"收入降收"},
			            {"id":"11", "parentid":"root", "topic":"语音费下降"},
				            {"id":"111", "parentid":"11", "topic":"有套餐(60人)"},
				            {"id":"112", "parentid":"11", "topic":"无套餐(80人)"},
		        ]      
var productMatchJSMindThumb = 	[
		            {"id":"root", "isroot":true, "topic":"流失预警"},
			            {"id":"11", "parentid":"root", "topic":"红包卡"},
				            {"id":"111", "parentid":"11", "topic":"大红包(60人)"},
				            {"id":"112", "parentid":"11", "topic":"小红包(80人)"},
				            {"id":"113", "parentid":"11", "topic":"至尊红包(80人)"},
		        ]      		         			        		       			       		        		        		        	      