// 导航数据
var leftMenu = [{
                    "children":[
                        {"href":"aaa","id":"1565","index":false,"menuType":"2","name":"模型报表","pid":"1528"},
                        {"href":"bbb","id":"1385","index":false,"menuType":"2","name":"报表设计器-研发","pid":"1528"},
                        {"href":"ccc","id":"2066","index":false,"menuClass":"","menuType":"2","name":"报表设置","pid":"1528"},
                        {"href":"ddd","id":"2105","index":false,"menuClass":"","menuType":"2","name":"移网存量监控","pid":"1528"}
                    ],
                    "href":"",
                    "id":"1528",
                    "index":false,
                    "menuClass":"monitor_report",
                    "menuType":"1",
                    "name":"监控报表",
                    "pid":"0"
                },{
                    "children":[
                        {"href":"eee","id":"3048","index":false,"menuClass":"","menuType":"2","name":"演示首页","pid":"3066"},
                        {"href":"fff","id":"3057","index":false,"menuClass":"","menuType":"2","name":"新版演示首页","pid":"3066"},
                        {"href":"ggg","id":"3058","index":false,"menuClass":"","menuType":"2","name":"大皮","pid":"3066"},
                        {"href":"hhh","id":"3059","index":false,"menuClass":"","menuType":"2","name":"模型","pid":"3066"}
                    ],
                    "href":"",
                    "id":"3066",
                    "index":false,
                    "menuClass":"nav_defalt",
                    "menuType":"1",
                    "name":"演示功能",
                    "pid":"0"
                },{
                    "children":[
                        {"href":"iii","id":"2907","index":false,"menuClass":"","menuType":"2","name":"清单发布v2","pid":"8"},
                        {"href":"jjj","id":"2910","index":false,"menuClass":"","menuType":"2","name":"清单查询v2","pid":"8"},
                        {"href":"kkk","id":"2911","index":false,"menuClass":"","menuType":"2","name":"清单下载v2","pid":"8"},
                        {"href":"lll","id":"2625","index":false,"menuClass":"","menuType":"2","name":"清单发布","pid":"8"},
                        {"href":"mmm","id":"1209","index":false,"menuClass":"","menuType":"2","name":"清单下载","pid":"8"},
                        {"href":"nnn","id":"1205","index":false,"menuType":"2","name":"清单查询","pid":"8"},
                        {"href":"ooo","id":"1926","index":false,"menuClass":"","menuType":"2","name":"发布文件","pid":"8"},
                        {"href":"ppp","id":"1928","index":false,"menuClass":"","menuType":"2","name":"发布文件查询","pid":"8"},
                        {"href":"qqq","id":"2271","index":false,"menuClass":"","menuType":"2","name":"MP3发布","pid":"8"}
                    ],
                    "href":"",
                    "id":"8",
                    "index":false,
                    "menuClass":"list_push",
                    "menuType":"1",
                    "name":"清单推送",
                    "pid":"0"
                },{
                    "children":[
                        {"href":"rrr","id":"1618","index":false,"menuClass":"","menuType":"2","name":"标签库","pid":"1617"},
                        {"href":"sss","id":"2669","index":false,"menuClass":"","menuType":"2","name":"cmcc自助报表Pro","pid":"1617"},
                        {"href":"ttt","id":"2985","index":false,"menuClass":"","menuType":"2","name":"我的看板","pid":"1617"},
                        {"href":"uuu","id":"1847","index":false,"menuClass":"","menuType":"2","name":"自助报表","pid":"1617"},
                        {"href":"vvv","id":"2671","index":false,"menuClass":"","menuType":"2","name":"自助报表Plus*","pid":"1617"},
                        {"href":"www","id":"2545","index":false,"menuClass":"","menuType":"2","name":"自助报表Pro","pid":"1617"},
                        {"href":"xxx","id":"2427","index":false,"menuClass":"","menuType":"2","name":"高级标签库","pid":"1617"},
                        {"href":"yyy","id":"3053","index":false,"menuClass":"","menuType":"2","name":"集团演示1","pid":"1617"},
                        {"href":"zzz","id":"1846","index":false,"menuClass":"","menuType":"2","name":"目标用户监控（旧）","pid":"1617"},
                        {"href":"111","id":"1845","index":false,"menuClass":"","menuType":"2","name":"自助查询（旧）","pid":"1617"},
                        {"href":"222","id":"2548","index":false,"menuClass":"","menuType":"2","name":"标签提取审批","pid":"1617"},
                        {"href":"333","id":"2549","index":false,"menuClass":"","menuType":"2","name":"标签提取下载","pid":"1617"}
                    ],
                    "href":"",
                    "id":"1617",
                    "index":false,
                    "menuClass":"tag_filter",
                    "menuType":"1",
                    "name":"自助分析",
                    "pid":"0"
                },{
                    "children":[
                        {"href":"aaaa","id":"1586","index":false,"menuClass":"","menuType":"2","name":"存量降收分析","pid":"1585"},
                        {"href":"bbbb","id":"2426","index":false,"menuClass":"","menuType":"2","name":"存量降收分析2","pid":"1585"},
                        {"href":"cccc","id":"1594","index":false,"menuType":"2","name":"收入结构分析","pid":"1585"},
                        {"href":"dddd","id":"1620","index":false,"menuType":"2","name":"产品结构","pid":"1585"},
                        {"href":"eeee","id":"2167","index":false,"menuClass":"","menuType":"2","name":"产品排行榜","pid":"1585"},
                        {"href":"ffff","id":"2886","index":false,"menuClass":"","menuType":"2","name":"收入波动-广西","pid":"1585"},
                        {"href":"gggg","id":"2065","index":false,"menuClass":"","menuType":"2","name":"收入波动分析","pid":"1585"},
                        {"href":"hhhh","id":"2346","index":false,"menuClass":"","menuType":"2","name":"收入波动分析_吉林","pid":"1585"},
                        {
                            "children":[
                                {"href":"iiii","id":"1586","index":false,"menuClass":"","menuType":"2","name":"存量降收分析","pid":"1585"},
                                {"href":"jjjj","id":"2426","index":false,"menuClass":"","menuType":"2","name":"存量降收分析2","pid":"1585"}
                            ],
                            "href":"","id":"2865","index":false,"menuClass":"","menuType":"2","name":"降收分析0730","pid":"1585"},
                    ],
                    "href":"",
                    "id":"1585",
                    "index":false,
                    "menuClass":"operation_analysis",
                    "menuType":"1",
                    "name":"运营分析",
                    "pid":"0"
                }]